### PR TITLE
added reactive ColorToDepthImage node

### PR DESCRIPTION
**Pull request by mhusinsky**
the ColorToDepthImage currently only exists as a non-reactive version, while the others (color, depth, infrared) have reactive versions as well.
i added it in the 'experimental' category where the original node resides too.

### CODE REVIEW

**Comment by joreg** [comment]
there is also a DepthToColor node.. any reason not to treat it the same way?

and please increase the version in the deployment\VL.Devices.AzureKinect.nuspec to 1.4.2 so when we accept the PR it builds a new pack automatically.

**Comment by mhusinsky** [comment]
the DepthToColor node was not working for me (threw exceptions all the time). it took me a while to figure out why - some nodes seem to receive the data (e.g. transformation) later and then won't update. using the cache region also for the transformation input seems to have solved the issue, all nodes now work as expected.


in the course of updating the nodes I also rewrote the PointCloudImage nodes and their respective C# functions. since the original version would truncate the depth data from 16 to 8 Bit I added an additional PointCloudImage16 node that does not do this and returns a R16G16B16A16F image (note, the original version is BGRA!). I'm still a little confused though as they basically look the same (except for the higher bit resolution of course).

grafik

**Comment by mhusinsky** [comment]
in my opinion we could also now consider to remove the experimental aspect (and make them advanced instead). however, we'd need to make some new helppatches for it then...
what do you think?

**Comment by joreg** [comment]
thanks, looking good!

and yes, please remove the experimental label if you're confident. adding helppatches on top would be great.

**Comment by joreg** [comment]
"I'm still a little confused though as they basically look the same (except for the higher bit resolution of course)."
i'd say this is exactly as it's supposed to be. the added bit depth is nothing you'd see.

**Comment by mhusinsky** [comment]
continued [here](https://github.com/vvvv/VL.Devices.AzureKinect/pull/5)...

**Pull request closed without merging**
